### ISSUE TITLE
Bug related to line intersections

### ISSUE THREAD

**Issue by MrClement** [alexoro412/optics#1]
### Description:
It seems like the lenses/mirrors are composed of multiple lines and they do not perfectly overlap.

### Example:
From "Reflection on a half sphere"
![image](https://user-images.githubusercontent.com/2237112/40257467-8075b7c6-5aab-11e8-92a1-1b99f5853d9c.png)

**Comment by alexoro412** [comment]
Should be fixed now

**Comment by alexoro412** [comment]
Nope, it's back, but on the parabola this time.
